apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-work-manifests
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /clusterzero/manifests
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-work-manifests
  namespace: tink-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scaffold-agent-4
  namespace: tink-system
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/kubefirst/scaffold-agent:7e5279f
          imagePullPolicy: IfNotPresent
          name: scaffold-agent
          args:
            - bootstrap
            - --apikey
            - "allfour"
          env:
            - name: "KUBEFIRST_DEBUG"
              value: "true"
          volumeMounts:
            - mountPath: "/home/vagrant/tokenized"
              name: work-tokenized
            - mountPath: "/home/vagrant/manifests"
              name: work-manifests
      restartPolicy: OnFailure
      serviceAccountName: scaffold-agent
      imagePullSecrets:
        - name: github-com
      volumes:
        - name: work-tokenized
          configMap:
            name: tokenized-files
        - name: work-manifests
          persistentVolumeClaim:
            claimName: pvc-work-manifests
#          emptyDir: {}
